### ISSUE TITLE
Упаковать конечное приложение в executable 

### ISSUE THREAD

**Issue by rosshkaa** [rosshkaa/XslXsdPlugChecker#8]
Насколько у конечной аудитории подготовлена среда (jre)? Не будет ли удобнее сразу оборачивать в ехе через какой-нибудь JSmooth или Launch4j?

**Comment by alexript** [comment]
Это внутренняя тулза. У нас тут у всех jre есть.
А еще у нас есть свой контейнер https://github.com/alexript/cocoon
